# Lab Exercise 1

Import basic libraries

In [ ]:
import numpy as np
import pandas as pd

Neural Network Libraries

In [ ]:
import tensorflow as tf
from tensorflow import keras

scikit-learn (helper tools)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score,
                             recall_score, f1_score,
                             confusion_matrix, classification_report)

Load the dataset

In [ ]:
df = pd.read_csv('/content/diabetes.csv')

print("Shape:", df.shape)

Shape: (768, 9)

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
print(df['Outcome'].value_counts())

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Removeing Fake values

In [ ]:
cols_to_check = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in cols_to_check:
    zero_count = (df[col] == 0).sum()
    print(f"{col:30} has {zero_count} zeros")

Glucose                        has 5 zeros
BloodPressure                  has 35 zeros
SkinThickness                  has 227 zeros
Insulin                        has 374 zeros
BMI                            has 11 zeros

In [ ]:
# Replace fake zeros with the median value of each column
cols_to_fix = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in cols_to_fix:
    median_value = df[col].median()
    df[col] = df[col].replace(0, median_value)

In [ ]:
for col in cols_to_fix:
    zero_count = (df[col] == 0).sum()
    print(f"{col:30} zeros remaining: {zero_count}")

Glucose                        zeros remaining: 0
BloodPressure                  zeros remaining: 0
SkinThickness                  zeros remaining: 0
Insulin                        zeros remaining: 0
BMI                            zeros remaining: 0

 Normalize the Features

In [ ]:
X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (768, 8)
y shape: (768,)

In [ ]:
print("Before normalization:")
print(f"  Age range:     {X[:,7].min():.0f}  to  {X[:,7].max():.0f}")
print(f"  Insulin range: {X[:,4].min():.0f}  to  {X[:,4].max():.0f}")

Before normalization:
  Age range:     21  to  81
  Insulin range: 14  to  846

In [ ]:
# Normalize using StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:

print("After normalization:")
print(f"  Age mean:     {X_scaled[:,7].mean():.4f}  ")
print(f"  Insulin mean: {X_scaled[:,4].mean():.4f}  ")
print(f"  Age std:      {X_scaled[:,7].std():.4f}  ")
print(f"  Insulin std:  {X_scaled[:,4].std():.4f}   ")

After normalization:
  Age mean:     0.0000
  Insulin mean: 0.0000
  Age std:      1.0000
  Insulin std:  1.0000

 Split into Training and Testing Sets

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
)

print("Training samples:", X_train.shape[0])
print("Testing samples: ", X_test.shape[0])

Training samples: 614
Testing samples:  154

In [ ]:
# Check class balance in both sets
train_diabetes = y_train.sum()
test_diabetes  = y_test.sum()

print("Training set:")
print(f"  Healthy (0): {len(y_train) - train_diabetes}  |  Diabetic (1): {train_diabetes}")

print("\nTesting set:")
print(f"  Healthy (0): {len(y_test) - test_diabetes}  |  Diabetic (1): {test_diabetes}")

Training set:
  Healthy (0): 401  |  Diabetic (1): 213

Testing set:
  Healthy (0): 99  |  Diabetic (1): 55

Build the neural network

In [ ]:
model = keras.Sequential([

    # Hidden layer 1
    # 16 neurons, takes 8 inputs, ReLU activation
    layers.Dense(16, activation='relu', input_shape=(8,), name='Hidden_Layer_1'),

    # Hidden layer 2
    # 8 neurons, ReLU activation
    layers.Dense(8, activation='relu', name='Hidden_Layer_2'),

    # Output layer
    # 1 neuron, Sigmoid activation (gives probability between 0 and 1)
    layers.Dense(1, activation='sigmoid', name='Output_Layer')

])

# Display a summary of the model
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden_Layer_1 (Dense)          │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

Compile the Model

In [ ]:
# Compile the model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

Train the Model

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.3623 - loss: 0.7655 - val_accuracy: 0.5161 - val_loss: 0.7018
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4783 - loss: 0.7177 - val_accuracy: 0.6290 - val_loss: 0.6815
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5996 - loss: 0.6882 - val_accuracy: 0.6935 - val_loss: 0.6684
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6576 - loss: 0.6672 - val_accuracy: 0.7097 - val_loss: 0.6566
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6812 - loss: 0.6490 - val_accuracy: 0.7258 - val_loss: 0.6445
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7047 - loss: 0.6312 - val_accuracy: 0.7097 - val_loss: 0.6322
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7283 - loss: 0.6127 - val_accuracy: 0.7419 - val_loss: 0.6168
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7409 - loss: 0.5934 - val_accuracy: 0.7097 - val_loss: 0.6015
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7428 - loss: 0.5735 - val_accuracy: 0.6935 - val_loss: 0.5893
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7554 - loss: 0.5551 - val_accuracy: 0.6935 - val_loss: 0.5763
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7663 - loss: 0.5372 - val_accuracy: 0.6935 - val_loss: 0.5642
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7663 - loss: 0.5231 - val_accuracy: 0.6774 - val_loss: 0.5589
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7645 - loss: 0.5097 - val_accuracy: 0.7097 - val_loss: 0.5499
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7681 - loss: 0.4992 - val_accuracy: 0.7097 - val_loss: 0.5423
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7681 - loss: 0.4895 - val_accuracy: 0.7097 - val_loss: 0.5382
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7717 - loss: 0.4826 - val_accuracy: 0.6935 - val_loss: 0.5346
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7681 - loss: 0.4766 - val_accuracy: 0.7097 - val_loss: 0.5312
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7772 - loss: 0.4710 - val_accuracy: 0.7097 - val_loss: 0.5248
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4673 - val_accuracy: 0.7097 - val_loss: 0.5239
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4639 - val_accuracy: 0.7258 - val_loss: 0.5276
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4610 - val_accuracy: 0.7097 - val_loss: 0.5253
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4597 - val_accuracy: 0.7258 - val_loss: 0.5215
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7862 - loss: 0.4552 - val_accuracy: 0.7097 - val_loss: 0.5268
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7844 - loss: 0.4537 - val_accuracy: 0.7097 - val_loss: 0.5245
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7844 - loss: 0.4524 - val_accuracy: 0.7097 - val_loss: 0.5208
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4499 - val_accuracy: 0.6935 - val_loss: 0.5193
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4482 - val_accuracy: 0.7097 - val_loss: 0.5186
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4471 - val_accuracy: 0.7097 - val_loss: 0.5182
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4454 - val_accuracy: 0.7258 - val_loss: 0.5164
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4440 - val_accuracy: 0.7097 - val_loss: 0.5172
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4430 - val_accuracy: 0.7258 - val_loss: 0.5166
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7844 - loss: 0.4432 - val_accuracy: 0.7258 - val_loss: 0.5235
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4402 - val_accuracy: 0.7097 - val_loss: 0.5199
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4389 - val_accuracy: 0.7097 - val_loss: 0.5164
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4380 - val_accuracy: 0.7258 - val_loss: 0.5171
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4363 - val_accuracy: 0.7097 - val_loss: 0.5210
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7808 - loss: 0.4355 - val_accuracy: 0.7097 - val_loss: 0.5215
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4346 - val_accuracy: 0.7097 - val_loss: 0.5227
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4333 - val_accuracy: 0.7258 - val_loss: 0.5220
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4324 - val_accuracy: 0.7097 - val_loss: 0.5217
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4317 - val_accuracy: 0.7097 - val_loss: 0.5194
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4301 - val_accuracy: 0.7097 - val_loss: 0.5199
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4294 - val_accuracy: 0.6935 - val_loss: 0.5193
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4285 - val_accuracy: 0.7097 - val_loss: 0.5191
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4274 - val_accuracy: 0.7258 - val_loss: 0.5190
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7935 - loss: 0.4263 - val_accuracy: 0.7258 - val_loss: 0.5212
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4269 - val_accuracy: 0.7097 - val_loss: 0.5228
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4253 - val_accuracy: 0.7258 - val_loss: 0.5189
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7935 - loss: 0.4234 - val_accuracy: 0.7258 - val_loss: 0.5215
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4226 - val_accuracy: 0.6935 - val_loss: 0.5225
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4212 - val_accuracy: 0.7097 - val_loss: 0.5234
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7917 - loss: 0.4212 - val_accuracy: 0.6935 - val_loss: 0.5249
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4201 - val_accuracy: 0.7258 - val_loss: 0.5246
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4188 - val_accuracy: 0.7258 - val_loss: 0.5229
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4176 - val_accuracy: 0.7097 - val_loss: 0.5259
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4169 - val_accuracy: 0.7097 - val_loss: 0.5247
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4158 - val_accuracy: 0.7258 - val_loss: 0.5235
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4152 - val_accuracy: 0.7097 - val_loss: 0.5255
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4143 - val_accuracy: 0.7097 - val_loss: 0.5235
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4133 - val_accuracy: 0.7097 - val_loss: 0.5244
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.4122 - val_accuracy: 0.7097 - val_loss: 0.5268
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.4117 - val_accuracy: 0.7097 - val_loss: 0.5279
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.4113 - val_accuracy: 0.7258 - val_loss: 0.5229
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4101 - val_accuracy: 0.7097 - val_loss: 0.5247
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4088 - val_accuracy: 0.7097 - val_loss: 0.5269
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7935 - loss: 0.4081 - val_accuracy: 0.7097 - val_loss: 0.5273
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7953 - loss: 0.4076 - val_accuracy: 0.7097 - val_loss: 0.5253
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7953 - loss: 0.4063 - val_accuracy: 0.7419 - val_loss: 0.5255
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8007 - loss: 0.4063 - val_accuracy: 0.7419 - val_loss: 0.5249
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8007 - loss: 0.4048 - val_accuracy: 0.7097 - val_loss: 0.5282
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7953 - loss: 0.4050 - val_accuracy: 0.7097 - val_loss: 0.5284
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8007 - loss: 0.4031 - val_accuracy: 0.7419 - val_loss: 0.5254
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7953 - loss: 0.4036 - val_accuracy: 0.7419 - val_loss: 0.5271
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7953 - loss: 0.4022 - val_accuracy: 0.7419 - val_loss: 0.5296
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8007 - loss: 0.4028 - val_accuracy: 0.7258 - val_loss: 0.5307
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8043 - loss: 0.4006 - val_accuracy: 0.7419 - val_loss: 0.5267
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8080 - loss: 0.4002 - val_accuracy: 0.7419 - val_loss: 0.5260
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8098 - loss: 0.4006 - val_accuracy: 0.7419 - val_loss: 0.5253
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8080 - loss: 0.3985 - val_accuracy: 0.7419 - val_loss: 0.5265
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3982 - val_accuracy: 0.7581 - val_loss: 0.5256
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3971 - val_accuracy: 0.7581 - val_loss: 0.5258
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8025 - loss: 0.3961 - val_accuracy: 0.7419 - val_loss: 0.5286
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.3958 - val_accuracy: 0.7419 - val_loss: 0.5280
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3948 - val_accuracy: 0.7419 - val_loss: 0.5274
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3940 - val_accuracy: 0.7419 - val_loss: 0.5271
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3930 - val_accuracy: 0.7419 - val_loss: 0.5283
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3939 - val_accuracy: 0.7581 - val_loss: 0.5301
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8080 - loss: 0.3925 - val_accuracy: 0.7581 - val_loss: 0.5280
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8098 - loss: 0.3919 - val_accuracy: 0.7581 - val_loss: 0.5273
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8098 - loss: 0.3909 - val_accuracy: 0.7581 - val_loss: 0.5290
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3907 - val_accuracy: 0.7419 - val_loss: 0.5294
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3894 - val_accuracy: 0.7581 - val_loss: 0.5295
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8098 - loss: 0.3887 - val_accuracy: 0.7581 - val_loss: 0.5299
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3880 - val_accuracy: 0.7581 - val_loss: 0.5321
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.3880 - val_accuracy: 0.7581 - val_loss: 0.5292
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.3869 - val_accuracy: 0.7581 - val_loss: 0.5294
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8098 - loss: 0.3867 - val_accuracy: 0.7581 - val_loss: 0.5289
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3861 - val_accuracy: 0.7581 - val_loss: 0.5287
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3849 - val_accuracy: 0.7581 - val_loss: 0.5331
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8152 - loss: 0.3843 - val_accuracy: 0.7581 - val_loss: 0.5324

Evaluate the Model

In [ ]:
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob >= 0.5).astype(int).flatten()

print("Predictions done!")

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
Predictions done!

Model Performance

In [ ]:
print(f"Accuracy  : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision : {precision_score(y_test, y_pred):.4f}")
print(f"Recall    : {recall_score(y_test, y_pred):.4f}")
print(f"F1-Score  : {f1_score(y_test, y_pred):.4f}")

Accuracy  : 0.7403
Precision : 0.6364
Recall    : 0.6364
F1-Score  : 0.6364

confusion matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print (cm )

[[79 20]
 [20 35]]

Classification report

In [ ]:
print(classification_report(y_test, y_pred,
      target_names=['No Diabetes', 'Diabetes']))

              precision    recall  f1-score   support

 No Diabetes       0.80      0.80      0.80        99
    Diabetes       0.64      0.64      0.64        55

    accuracy                           0.74       154
   macro avg       0.72      0.72      0.72       154
weighted avg       0.74      0.74      0.74       154

Train a Second Model with SGD

In [ ]:

model_sgd = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(8,), name='Hidden_Layer_1'),
    layers.Dense(8,  activation='relu', name='Hidden_Layer_2'),
    layers.Dense(1,  activation='sigmoid', name='Output_Layer')
])

# Compile with SGD instead of Adam
model_sgd.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train it
history_sgd = model_sgd.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6630 - loss: 0.6577 - val_accuracy: 0.6452 - val_loss: 0.6646
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6993 - loss: 0.6054 - val_accuracy: 0.6774 - val_loss: 0.6359
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7554 - loss: 0.5494 - val_accuracy: 0.6935 - val_loss: 0.5961
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7790 - loss: 0.5049 - val_accuracy: 0.6774 - val_loss: 0.5889
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7754 - loss: 0.4799 - val_accuracy: 0.7258 - val_loss: 0.5748
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7790 - loss: 0.4682 - val_accuracy: 0.7258 - val_loss: 0.5768
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4575 - val_accuracy: 0.7258 - val_loss: 0.5671
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4541 - val_accuracy: 0.7258 - val_loss: 0.5668
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4446 - val_accuracy: 0.7258 - val_loss: 0.5727
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7844 - loss: 0.4448 - val_accuracy: 0.7419 - val_loss: 0.5702
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4400 - val_accuracy: 0.7097 - val_loss: 0.5604
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4307 - val_accuracy: 0.7097 - val_loss: 0.5720
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7953 - loss: 0.4284 - val_accuracy: 0.7258 - val_loss: 0.5591
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4244 - val_accuracy: 0.7258 - val_loss: 0.5720
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4219 - val_accuracy: 0.7097 - val_loss: 0.5731
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7917 - loss: 0.4171 - val_accuracy: 0.7581 - val_loss: 0.5689
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7953 - loss: 0.4124 - val_accuracy: 0.7581 - val_loss: 0.5669
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7917 - loss: 0.4103 - val_accuracy: 0.7419 - val_loss: 0.5721
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7989 - loss: 0.4113 - val_accuracy: 0.7419 - val_loss: 0.5714
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8025 - loss: 0.4090 - val_accuracy: 0.7419 - val_loss: 0.5707
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7971 - loss: 0.4054 - val_accuracy: 0.7258 - val_loss: 0.5730
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8007 - loss: 0.4035 - val_accuracy: 0.7258 - val_loss: 0.5781
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7971 - loss: 0.4003 - val_accuracy: 0.7419 - val_loss: 0.5742
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8007 - loss: 0.4009 - val_accuracy: 0.7581 - val_loss: 0.5730
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7935 - loss: 0.3982 - val_accuracy: 0.7581 - val_loss: 0.5821
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8007 - loss: 0.3992 - val_accuracy: 0.7258 - val_loss: 0.5752
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8098 - loss: 0.3988 - val_accuracy: 0.7419 - val_loss: 0.5842
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8007 - loss: 0.4028 - val_accuracy: 0.7419 - val_loss: 0.5977
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8007 - loss: 0.3926 - val_accuracy: 0.7258 - val_loss: 0.5816
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.3950 - val_accuracy: 0.7258 - val_loss: 0.5834
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3941 - val_accuracy: 0.7258 - val_loss: 0.5848
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.3987 - val_accuracy: 0.7097 - val_loss: 0.6087
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8025 - loss: 0.3948 - val_accuracy: 0.7419 - val_loss: 0.5865
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.3909 - val_accuracy: 0.7258 - val_loss: 0.5767
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.3892 - val_accuracy: 0.7581 - val_loss: 0.5926
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7935 - loss: 0.3879 - val_accuracy: 0.7258 - val_loss: 0.5901
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.3866 - val_accuracy: 0.7419 - val_loss: 0.5936
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.3849 - val_accuracy: 0.7258 - val_loss: 0.5940
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3862 - val_accuracy: 0.7258 - val_loss: 0.5909
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3852 - val_accuracy: 0.7419 - val_loss: 0.5945
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3833 - val_accuracy: 0.7419 - val_loss: 0.6025
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8025 - loss: 0.3820 - val_accuracy: 0.7419 - val_loss: 0.5997
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8080 - loss: 0.3813 - val_accuracy: 0.7419 - val_loss: 0.5992
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.3789 - val_accuracy: 0.7419 - val_loss: 0.5999
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.3781 - val_accuracy: 0.7419 - val_loss: 0.6000
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8152 - loss: 0.3793 - val_accuracy: 0.7419 - val_loss: 0.5996
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8098 - loss: 0.3787 - val_accuracy: 0.7419 - val_loss: 0.5955
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8025 - loss: 0.3808 - val_accuracy: 0.7419 - val_loss: 0.5977
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8170 - loss: 0.3779 - val_accuracy: 0.7258 - val_loss: 0.6202
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3796 - val_accuracy: 0.7419 - val_loss: 0.6028
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.3760 - val_accuracy: 0.7419 - val_loss: 0.6014
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3747 - val_accuracy: 0.7419 - val_loss: 0.6048
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8170 - loss: 0.3729 - val_accuracy: 0.7581 - val_loss: 0.6093
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8207 - loss: 0.3752 - val_accuracy: 0.7419 - val_loss: 0.6233
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8170 - loss: 0.3728 - val_accuracy: 0.7258 - val_loss: 0.6026
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8170 - loss: 0.3698 - val_accuracy: 0.7419 - val_loss: 0.6140
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3747 - val_accuracy: 0.7258 - val_loss: 0.6046
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3686 - val_accuracy: 0.7581 - val_loss: 0.6178
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8152 - loss: 0.3721 - val_accuracy: 0.7419 - val_loss: 0.6097
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8116 - loss: 0.3698 - val_accuracy: 0.7581 - val_loss: 0.6282
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3747 - val_accuracy: 0.7258 - val_loss: 0.6060
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8170 - loss: 0.3658 - val_accuracy: 0.7419 - val_loss: 0.5925
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3652 - val_accuracy: 0.7581 - val_loss: 0.6131
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.3644 - val_accuracy: 0.7419 - val_loss: 0.5988
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.3616 - val_accuracy: 0.7419 - val_loss: 0.6028
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3623 - val_accuracy: 0.7419 - val_loss: 0.6150
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3609 - val_accuracy: 0.7419 - val_loss: 0.6106
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8279 - loss: 0.3591 - val_accuracy: 0.7419 - val_loss: 0.6270
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.3576 - val_accuracy: 0.7419 - val_loss: 0.6155
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8152 - loss: 0.3597 - val_accuracy: 0.7419 - val_loss: 0.6330
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8243 - loss: 0.3548 - val_accuracy: 0.7419 - val_loss: 0.6106
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3643 - val_accuracy: 0.7419 - val_loss: 0.6218
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8207 - loss: 0.3587 - val_accuracy: 0.7419 - val_loss: 0.6220
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.3550 - val_accuracy: 0.7419 - val_loss: 0.6337
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8315 - loss: 0.3551 - val_accuracy: 0.7419 - val_loss: 0.6173
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8279 - loss: 0.3510 - val_accuracy: 0.7419 - val_loss: 0.6348
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.3486 - val_accuracy: 0.7419 - val_loss: 0.6287
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8279 - loss: 0.3533 - val_accuracy: 0.7419 - val_loss: 0.6262
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8279 - loss: 0.3564 - val_accuracy: 0.7419 - val_loss: 0.6295
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.3518 - val_accuracy: 0.7419 - val_loss: 0.6462
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8370 - loss: 0.3523 - val_accuracy: 0.7419 - val_loss: 0.6277
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3506 - val_accuracy: 0.7419 - val_loss: 0.6284
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8370 - loss: 0.3443 - val_accuracy: 0.7419 - val_loss: 0.6479
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8370 - loss: 0.3503 - val_accuracy: 0.7419 - val_loss: 0.6427
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8351 - loss: 0.3437 - val_accuracy: 0.7419 - val_loss: 0.6263
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8370 - loss: 0.3425 - val_accuracy: 0.7419 - val_loss: 0.6380
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3404 - val_accuracy: 0.7419 - val_loss: 0.6312
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3431 - val_accuracy: 0.7419 - val_loss: 0.6341
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8442 - loss: 0.3406 - val_accuracy: 0.7419 - val_loss: 0.6317
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.3451 - val_accuracy: 0.7419 - val_loss: 0.6406
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8406 - loss: 0.3393 - val_accuracy: 0.7419 - val_loss: 0.6552
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8478 - loss: 0.3388 - val_accuracy: 0.7419 - val_loss: 0.6458
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8406 - loss: 0.3378 - val_accuracy: 0.7419 - val_loss: 0.6402
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8460 - loss: 0.3363 - val_accuracy: 0.7258 - val_loss: 0.6355
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8478 - loss: 0.3393 - val_accuracy: 0.7419 - val_loss: 0.6263
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8406 - loss: 0.3340 - val_accuracy: 0.7419 - val_loss: 0.6371
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8478 - loss: 0.3317 - val_accuracy: 0.7419 - val_loss: 0.6580
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8460 - loss: 0.3307 - val_accuracy: 0.7419 - val_loss: 0.6459
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3329 - val_accuracy: 0.7419 - val_loss: 0.6233
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8533 - loss: 0.3274 - val_accuracy: 0.7419 - val_loss: 0.6373

Evaluate SGD model

In [ ]:
y_pred_prob_sgd = model_sgd.predict(X_test)
y_pred_sgd = (y_pred_prob_sgd >= 0.5).astype(int).flatten()

print(" SGD MODEL PERFORMANCE ")
print(f"Accuracy  : {accuracy_score(y_test, y_pred_sgd):.4f}")
print(f"Precision : {precision_score(y_test, y_pred_sgd):.4f}")
print(f"Recall    : {recall_score(y_test, y_pred_sgd):.4f}")
print(f"F1-Score  : {f1_score(y_test, y_pred_sgd):.4f}")

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step
 SGD MODEL PERFORMANCE
Accuracy  : 0.7013
Precision : 0.5789
Recall    : 0.6000
F1-Score  : 0.5893

Comparison

In [ ]:

print(f"{'Metric':15} {'Adam':>10} {'SGD':>10}")
print("")
print(f"{'Accuracy':15} {accuracy_score(y_test, y_pred):>10.4f} {accuracy_score(y_test, y_pred_sgd):>10.4f}")
print(f"{'Precision':15} {precision_score(y_test, y_pred):>10.4f} {precision_score(y_test, y_pred_sgd):>10.4f}")
print(f"{'Recall':15} {recall_score(y_test, y_pred):>10.4f} {recall_score(y_test, y_pred_sgd):>10.4f}")
print(f"{'F1-Score':15} {f1_score(y_test, y_pred):>10.4f} {f1_score(y_test, y_pred_sgd):>10.4f}")

Metric                Adam        SGD

Accuracy            0.7403     0.7013
Precision           0.6364     0.5789
Recall              0.6364     0.6000
F1-Score            0.6364     0.5893